### ISSUE TITLE
Compile Problem

### ISSUE THREAD

**Issue by morpheusbeing** [RetroShare/Lua4RS#1]
Debian Testing. Qt5.4.2.

lpthread  
/usr/bin/ld: //usr/local/lib/liblua.a(lapi.o): relocation R_X86_64_32 against `luaO_nilobject_' can not be used when making a shared object; recompile with -fPIC
//usr/local/lib/liblua.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:227: recipe for target 'libLua4RS.so.1.0.0' failed
make: **\* [libLua4RS.so.1.0.0] Error 1

Not sure what this means with -fPIC and where to put. Some guidance please

**Comment by sehraf** [comment]
I'm closing the bug report for now since it looks like a bug in your setup (see RS forum).
When you find something useful feel free to reopen it.

**Comment by sehraf** [comment]
solution: see #2
