### ISSUE TITLE
git issue with commits

### ISSUE THREAD

**Issue by morpheusbeing** [RetroShare/Lua4RS#3]
Did into new download if RS:
    git pull https://github.com/RetroShare/Lua4RS.git
Got back:
    warning: no common commits
    remote: Counting objects: 1513, done.
    Receiving objects: 100% (1513/1513), 308.90 KiB | 182.00 KiB/s, done.
    remote: Total 1513 (delta 0), reused 0 (delta 0), pack-reused 1513
    Resolving deltas: 100% (1128/1128), done.
    From https://github.com/RetroShare/Lua4RS
    * branch                HEAD       -> FETCH_HEAD
    fatal: refusing to merge unrelated histories

**Comment by sehraf** [comment]
I think you are confusing "git pull" with "gut clone" ;) 

Am 2. März 2017 08:30:59 MEZ schrieb Morpheus Being <notifications@github.com>:
>Did into new download if RS:
>    git pull https://github.com/RetroShare/Lua4RS.git
>Got back:
>    warning: no common commits
>    remote: Counting objects: 1513, done.
>  Receiving objects: 100% (1513/1513), 308.90 KiB | 182.00 KiB/s, done.
>    remote: Total 1513 (delta 0), reused 0 (delta 0), pack-reused 1513
>    Resolving deltas: 100% (1128/1128), done.
>    From https://github.com/RetroShare/Lua4RS
>    * branch                HEAD       -> FETCH_HEAD
>    fatal: refusing to merge unrelated histories
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/RetroShare/Lua4RS/issues/3

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by morpheusbeing** [comment]
You are correct, I made a mistake,
