### ISSUE TITLE
Issues with compile with latest RS

### ISSUE THREAD

**Issue by morpheusbeing** [RetroShare/Lua4RS#4]
In file included from ../../libretroshare/src/retroshare/rsidentity.h:33:0,
                 from Lua4RSNotify.cpp:1:
../../libretroshare/src/retroshare/rstokenservice.h:65:3: warning: #warning RS_TOKREQ_ANSTYPE_* macros are deprecated! [-Wcpp]
 # warning RS_TOKREQ_ANSTYPE_* macros are deprecated!
   ^~~~~~~
g++ -c -m64 -pipe -O2 -D_REENTRANT -Wall -W -fPIC -DRS_ENABLE_GXS -DENABLE_WEBUI -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../libretroshare/src -I../../retroshare-gui/src -isystem /usr/include/lua5.2 -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o Lua4RSWidget.o gui/Lua4RSWidget.cpp
gui/Lua4RSWidget.cpp: In constructor ‘Lua4RSWidget::Lua4RSWidget(QWidget*)’:
gui/Lua4RSWidget.cpp:57:48: error: no matching function for call to ‘Lua4RSWidget::registerHelpButton(QToolButton*&, QString&)’
     registerHelpButton(ui->helpButton, help_str);
                                                ^
In file included from gui/Lua4RSWidget.h:4:0,
                 from gui/Lua4RSWidget.cpp:10:
../../retroshare-gui/src/retroshare-gui/mainpage.h:64:7: note: candidate: void MainPage::registerHelpButton(QToolButton*, const QString&, const QString&)
  void registerHelpButton(QToolButton *button, const QString& help_html_text, const QString &code_name) ;
       ^~~~~~~~~~~~~~~~~~
../../retroshare-gui/src/retroshare-gui/mainpage.h:64:7: note:   candidate expects 3 arguments, 2 provided
Makefile:612: recipe for target 'Lua4RSWidget.o' failed

**Comment by sehraf** [comment]
fixed by 66ecb3aa83907c085719695436ec2788d16f4a3e
